eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
server:
  port: 9999
spring:
  application:
    name: composite-product

core-product:
  ribbon:
    eureka:
      enabled: true
#    listOfServers: "localhost:9090"