eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
#server:
#  port: 9999
app:
  jwt:
    public-key: "classpath:public.txt"
spring:
  application:
    name: composite-product
